apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pr-gatekeeper
  labels:
    app: pr-gatekeeper
    app.kubernetes.io/name: pr-gatekeeper
    app.kubernetes.io/component: trigger-template
    app.kubernetes.io/instance: pr-gatekeeper
    app.kubernetes.io/part-of: pr-gatekeeper
    application.giantswarm.io/team: team-tinkerers
  annotations:
    tekton.dev/tags: github, pull request
spec:
  params:
  - name: PR
  - name: REPO
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: TaskRun
      metadata:
        generateName: pr-gatekeeper-
      spec:
        taskRef:
          kind: Task
          name: pr-gatekeeper
        params:
        - name: PR
          value: $(tt.params.PR)
        - name: REPO
          value: $(tt.params.REPO)
        podTemplate:
          imagePullSecrets:
            - name: quay-imagepull-secret
