version: 2.1

orbs:
  architect: giantswarm/architect@5.13.1

workflows:
  build-and-publish:
    jobs:
      - architect/go-test:
          context: architect
          name: go-test
          resource_class: medium
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-test
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
            branches:
              only: main
