version: 2.1

orbs:
  architect: giantswarm/architect@4.29.0

workflows:
  test:
    build-and-publish:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

  build-and-publish:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: pr-gatekeeper
          resource_class: xlarge
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: architect
          name: push-pr-gatekeeper-to-quay
          image: "quay.io/giantswarm/pr-gatekeeper"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
          - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-pr-gatekeeper-to-docker
          image: "docker.io/giantswarm/pr-gatekeeper"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
